# PyTorch Fundamentals

In this notebook i'll be learning PyTorch and practicing the fundamentals? 

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.2.2+cu118


In [2]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

Using device: cuda


## Introduction to Tensors

### Creating Tensors

Tensors in PyTorch and ML i general refer simply to Multidimensional arrays that support algebraic operations.

One can create PyTorch tensors using `torch.tensor()`.
Read More: https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Vector
vec = torch.tensor([2, 9])
vec

tensor([2, 9])

In [6]:
vec.ndim

1

In [7]:
# MATRIX
MATRIX = torch.tensor([[3, 8], [6, 9]])
MATRIX

tensor([[3, 8],
        [6, 9]])

In [8]:
MATRIX.ndim

2

In [9]:
# TENSOR (3D+)
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [10]:
TENSOR.ndim

3

### Random Tensors

Why would you want a random tensor?

Many neural networks require starting with a randomized tensor so it can adjust them to represent the data more accuratly.

In [21]:
# Create a random tensor of size (4, 5)
random_tensor = torch.rand(4, 5)
random_tensor

tensor([[0.6551, 0.5484, 0.2434, 0.9424, 0.9975],
        [0.0857, 0.4722, 0.4239, 0.2258, 0.9056],
        [0.1179, 0.9911, 0.8314, 0.5813, 0.0083],
        [0.3321, 0.1065, 0.5113, 0.3340, 0.3915]])

In [22]:
random_tensor.multiply(10)

tensor([[6.5509, 5.4837, 2.4343, 9.4236, 9.9755],
        [0.8575, 4.7216, 4.2390, 2.2576, 9.0562],
        [1.1793, 9.9113, 8.3143, 5.8134, 0.0833],
        [3.3212, 1.0654, 5.1127, 3.3400, 3.9154]])

In [23]:
random_tensor.ndim

2